apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: cep-project1
  labels:
    app: wordpress
    tier: frontend
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /srv/nfs_client/volume 
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteMany

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: cep-project1
  labels:
    app: wordpress
    tier: mysql
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /srv/nfs_client/mysql
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteMany